### ISSUE TITLE
Feed back to letter-writers when a CV they requested is uploaded

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#11]
I’ve changed my mind on this multiple times – apologies!

As a letter-writer, it would be super awesome to get a bit of positive reinforcement when my letter **works** and the candidate uploads their CV.

I’d also love to know there’s a new CV for me to read! But I think you were intending to do that bit anyway, using the “updates” feature.

**Comment by amcewen** [comment]
The "updates" feature?  Is that live yet?  I was going to raise an issue asking for an RSS feed or (probably more useful for the rest of the world ;-) an "email me updates to this constituency" option, but this seems to cover things really.  So just registering my "this sounds good".

**Comment by frabcus** [comment]
It exists but perhaps not in the form you want - after emailing candidates
you get the option to sign up for updates.

The are not totally automatic, but do tell you about new CVs.

**Comment by frabcus** [comment]
I've changed it to show you updates after Tweeting everyone, which would hit another workflow.

I've made a note to pay attention to updates in general redesign.
