### ISSUE TITLE
Subscribe to constituency updates, not postcode updates

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#13]
I don’t think you need to [store my postcode](https://github.com/frabcus/mpcv/blob/66f271f8/lookups.py#L200) when I subscribe to updates; just my constituency.

**Comment by frabcus** [comment]
On the contrary, I'm deliberately storing your postcode.

There's a high chance your constituency will have changed at the next election.

**Comment by frabcus** [comment]
Just to ask - is it for privacy reasons you're concerned?

**Comment by andylolz** [comment]
> There's a high chance your constituency will have changed at the next election.

Ahh – I thought you might say that. So… That’s fine, but I think you should be explicit in the copy that you’re storing it. With the election so close, I very much felt like I was signing up to something ephemeral. (There’s also a very high chance my postcode will be different by the next election. 5 years is a long time when you rent!)

> Just to ask - is it for privacy reasons you're concerned?

I suppose… Well not really, actually. I was just surprised this wasn’t more transparent.

**Comment by andylolz** [comment]
asdf
