### ISSUE TITLE
Add some compelling Open Graph metadata

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#18]
Facebook shares look like this at the moment:

![screen shot 2015-03-11 at 13 59 09](https://cloud.githubusercontent.com/assets/464193/6597796/d793a478-c7f6-11e4-975c-e83de64ea401.png)

**Comment by frabcus** [comment]
Do I just need these two?

```
   <meta property="og:title" content="38 Degrees Election Hub" />
    <meta property="og:image" content="https://s.bsd.net/38degrees/main/page/-/14929457840_1766da5c61_k.jpg" />
```

Any particular content for them?

**Comment by frabcus** [comment]
They have this too:

```
    <meta name="description" content="Make a difference in May 2015 - sign up to the 38 Degrees Election Hub!">
```

**Comment by frabcus** [comment]
I've added a bunch of tags, but <a href="https://developers.facebook.com/tools/debug/og/object/">Facebook's checker</a> says it will still look like this:

![image](https://cloud.githubusercontent.com/assets/10153/6654105/9d9f4fee-caa6-11e4-8a2f-24e02ab3d63d.png)

Not even the icon!  Any idea why, @andylolz ?

I was following the Minimal Template from http://moz.com/blog/meta-data-templates-123

**Comment by andylolz** [comment]
I believe the minimum image size is 200x200px.

**Comment by frabcus** [comment]
Hmmm, I tried the big version of the logo. I think we need a better picture :)

http://cv.democracyclub.org.uk/static/dc_logo_large.png

**Comment by frabcus** [comment]
I've put a CV thumbnail in.

**Comment by andylolz** [comment]
That’s really cool!

500 x 500px _should_ have been fine, not sure why that didn’t work.

**Comment by frabcus** [comment]
It worked, just looked cranky, wrong kind of image aesthetically. Think it
assumes it is  a photo at that size. It cropped it oddly.
