### ISSUE TITLE
It should be possible to link to a candidate's CV

### ISSUE THREAD

**Issue by amcewen** [frabcus/mpcv#2]
I know you stated that you deliberately haven't made it possible to look for famous people's CVs, but I think you're missing a useful marketing channel if you don't provide that.  

You needn't make it easy to browse/search for them, but I think allowing hyperlinks to a candidate once you do find them will help word of the app spread.  Obviously, if you arrive at the page from off-site, then you could add a paragraph or two of "about the site" plus buttons/links top and bottom to "I want to check my MPs" to then bring people into the real purpose of the site.

I haven't found a CV yet, so don't know if it is possible, figured I'd raise anyway.

**Comment by frabcus** [comment]
There aren't any yet as haven't quite got that far :)

Will make it possible to link once you've got to them, yep!

**Comment by frabcus** [comment]
This is definitely happening - closing now.
