### ISSUE TITLE
Partial postcode

### ISSUE THREAD

**Issue by jacattell** [frabcus/mpcv#3]
I'd like to search using just the 1st part of the postcode

**Comment by frabcus** [comment]
I think quite a lot of constituencies are ambiguous for that.

Can you say a bit more about why you don't want to put the whole postcode?

Just to say, partly I'm trying to make it only easy to see your own candidate's CVs so people concentrate on them. I don't particularly want concentration on famous people's CVs and so on.

**Comment by frabcus** [comment]
I asked Mark Longair and he says:

> mapit will give you the centroid of a partial postcode, e.g.: http://mapit.mysociety.org/postcode
> /partial/OX4 which you can then do a /point lookup on

But that it doesn't do it in one go because that isn't an accurate list of corresponding areas.

**Comment by frabcus** [comment]
I'm not going to fix this for now, sorry :(

Please feel free to reopen and explain why this is important!
