### ISSUE TITLE
Make it clear what is and isn’t a CV

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#30]
Many candidates have uploaded CVs that are not actually CVs.

How about something like this on the upload page:

| This _is_ a CV | This _isn't_ a CV |
| --- | --- |
| ![good](https://cloud.githubusercontent.com/assets/464193/6706975/50ba767a-cd5a-11e4-9ce8-328f546c3904.png) | ![bad](https://cloud.githubusercontent.com/assets/464193/6706977/53836f92-cd5a-11e4-9b4f-0a0eac8c0257.png) |
| Delineated list of jobs including dates and names of employers | List of jobs is in a block of text. No dates or employers given. |

**Comment by tfgg** [comment]
Looks great, nice and clear.

Perhaps also something making it clear that an election leaflet is not a CV, either? Not sure how to elegantly fit that into the two column is/isn't layout, though.

**Comment by frabcus** [comment]
We could have a third column "this isn't"  with an election leaflet with
cross.

And the text below link to election leaflets!

**Comment by frabcus** [comment]
Done!
