### ISSUE TITLE
PAGE_SIZE of 12 kills my machine

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#31]
…on http://cv.democracyclub.org.uk/all_cvs/page/1

Could you knock it down to 9 maybe? Or even lower?

**Comment by frabcus** [comment]
I initially had it at 9.

I changed to 12, as then I can have 4 or 3 columns according to
the width, and it still divides up.

I'd _love_ a way of it only showing thumbnail images, but can't
work out how to generate those from Google Viewer. Any idea?

Think it can't be done any more (used to be).

Could go for say 8 and do 4 and 2 columns?

Francis

On Wed, Mar 18, 2015 at 04:24:22AM -0700, Andy Lulham wrote:

> …on http://cv.democracyclub.org.uk/all_cvs/page/1
> 
> Could you knock it down to 9 maybe? Or even lower?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/frabcus/mpcv/issues/31

## 

Do _you_ have an awesome idea you never quite manage to do? 
http://www.awesomefoundation.org/en/chapters/liverpool/

**Comment by andylolz** [comment]
Much better – thanks!

I had a look at thumbnails from google reader and couldn’t figure it out either. I’ll take another look now.

**Comment by andylolz** [comment]
You could pass a google document viewer URL to http://webshot.okfnlabs.org/ ? (and cache the result.)
