### ISSUE TITLE
Thumbnails via Google Drive API

### ISSUE THREAD

**Issue by frabcus** [frabcus/mpcv#33]
If we upload to Google Drive, there's a getThumbnail API, see https://developers.google.com/apps-script/reference/drive/file#getThumbnail%28%29

**Comment by frabcus** [comment]
Think @andylolz is right that http://webshot.okfnlabs.org/ looks easier.

Or `node-webshot` which that uses internally http://webshot.okfnlabs.org/

**Comment by frabcus** [comment]
Wondering if there is a clever way of doing this by calling whatever JSON API the Google Viewer calls - certainly it quickly gets a nice PNG file as one of the first things it does, just with odd URLs.

e.g. https://docs.google.com/viewerng/img?id=ACFrOgCR9oxr_AzZj-1z41_o2GKNfWnurtPIBr_AmGWiD3Rp2hW7oiVlwf4RwmY0TcgjCBfWSMwl-CW9p_-GhjqbbRKtlY9GtSmYQQvJG9lXv2Np9bUe0P1TzVD0WZc=&u=0&w=800&page=0

**Comment by andylolz** [comment]
Resource unavailable :(
