### ISSUE TITLE
Vertical scrollbar not visible on full page CV view (Safari/OSX)

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#36]
e.g. http://cv.democracyclub.org.uk/show_cv/6214

Tested in Safari for Mac Version 7.1.4 (9537.85.13.7)

via @peterkwells

**Comment by frabcus** [comment]
Hmmm, I'm not sure what is going on.

Notably, the same bug strikes when using the Google Viewer directly.

https://docs.google.com/viewerng/viewer?url=https://mpcv.s3.amazonaws.com:443/cvs/6214/cv%2520Hugh%2520Lanham%25202013.doc

**Comment by frabcus** [comment]
In the course of investigating this, I fixed (well workaround some kind of minor unexpected padding with an overflow) the problem in Chrome with double scrollbars!

https://github.com/frabcus/mpcv/commit/efd0852c9f4d74dacac8c140c9e78bf9f27ed58d

That's now deployed if you want to try it out.

I'm closing this bug, as I think if it happens in Google Viewer, it is a flaw in Google Viewer. I can't see how to fix it. Maybe report bug in Google Viewer?
