### ISSUE TITLE
Display candidate info on All CVs page/recently added template?

### ISSUE THREAD

**Issue by rightsaidjames** [frabcus/mpcv#38]
At the moment the [All CVs](http://cv.democracyclub.org.uk/all_cvs/page/1) page displays a list of all uploaded CVs in the order they were uploaded (most recent first). However with the thumbnail-sized preview you often have to zoom in/squint to see the name at the top of the document, and unless the candidate has included this info on their CV there's no way to know their party or constituency. It would be good if this template displayed each candidate's name, party and constituency, either as a heading above the preview or above/below the 'View full page' link.

![2015-03-23 14_09_05-all cvs - democracy club cvs](https://cloud.githubusercontent.com/assets/3018395/6781529/39a5d2f8-d166-11e4-8669-18157ee309ff.png)

The same lack of candidate info issue exists for the 'recently added' view on the homepage, but due to the increased size of the preview you can usually read the candidate's name without zooming in or squinting.

![2015-03-23 14_10_01-curriculum vitae of future members of parliament - democracy club cvs](https://cloud.githubusercontent.com/assets/3018395/6781546/5a6ce1ca-d166-11e4-9def-1af86a294de4.png)

Happy to submit a pull request to add this functionality to the relevant templates, but wanted to check it was wanted first!

**Comment by frabcus** [comment]
Yep, so I was deliberately leaving this out for a while, to get people to concentrate on the CVs themselves, and to keep it simple.

You can tell I think this is silly really, as on the `/candidates` page it looks like this (South Cambs, use CB23 6EA postcode to see live).

![image](https://cloud.githubusercontent.com/assets/10153/6816420/ebe1aa58-d28a-11e4-9e3f-4b74e9b645ca.png)

With long names it is ugly on narrow browsers (mobile) though because the wrapping makes the whole layout jump about.

Yep, am up for doing it on all the pages, if you can make it fit and look good! Suspect it will be ace, just hasn't been an itch I have.

**Comment by rightsaidjames** [comment]
Ah, hadn't considered mobile - perhaps if the layout of CVs (on any overview-type page) was changed to 1 per row below a certain viewport width? This would solve the wrapping issue for long names:
![image](https://cloud.githubusercontent.com/assets/3018395/6825105/dd26d8fc-d2ef-11e4-9576-b0a75bfcee43.png)

Although a quick dig through your code and the Bootstrap docs suggests there isn't an easy way to do this without having massive thumbnails all the way up to 768px (the tablet breakpoint), which looks equally silly:
![mpcv big thumbnails](https://cloud.githubusercontent.com/assets/3018395/6825923/ee4bb638-d2f5-11e4-9598-e34a34cd85cd.gif)

I'll have a poke around and use what you have on the /candidates page as a guide for styling it up.

**Comment by frabcus** [comment]
I talked to a friend about this this morning.

One thing he said was that _the_ important thing on the front page /
all page is to show the constituency. Name and party are secondary.

Which is interesting - there are three potential pieces of
information. (Unlike /candidates which only has to show two)

It needs playing with to have something that works and isn't
cluttered.

Also, as a fallback if we can't do it, having a Bootstrap tooltip with
the information in it would be definitely a good idea.

Francis

On Wed, Mar 25, 2015 at 06:51:01AM -0700, James Thomas wrote:

> Ah, hadn't considered mobile - perhaps if the layout of CVs (on any overview-type page) was changed to 1 per row below a certain viewport width? This would solve the wrapping issue for long names:
> ![image](https://cloud.githubusercontent.com/assets/3018395/6825105/dd26d8fc-d2ef-11e4-9576-b0a75bfcee43.png)
> 
> Although a quick dig through your code and the Bootstrap docs suggests there isn't an easy way to do this without having massive thumbnails all the way up to 768px (the tablet breakpoint), which looks equally silly:
> ![mpcv big thumbnails](https://cloud.githubusercontent.com/assets/3018395/6825923/ee4bb638-d2f5-11e4-9598-e34a34cd85cd.gif)
> 
> I'll have a poke around and use what you have on the /candidates page as a guide for styling it up.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/frabcus/mpcv/issues/38#issuecomment-86035373

## 

Help get every MP candidate's Curriculum Vitae!
http://cv.democracyclub.org.uk/

**Comment by frabcus** [comment]
There's now a constituency list version of the all page.

http://cv.democracyclub.org.uk/all_cvs/alphabet/medium

Not sure it is quite right, but it has the info at least.
