### ISSUE TITLE
Explicitly declare no copyright on about page

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#44]
Licensing is currently not mentioned on the site. MaliciaRogue says (on twitter):

![screen shot 2015-03-25 at 10 46 34](https://cloud.githubusercontent.com/assets/464193/6823023/45db0cc4-d2dc-11e4-820e-be9f45a4aba0.png)

Also, currently no licence on code.

**Comment by frabcus** [comment]
I've added license to the code.

I don't feel like cluttering the page with "licensing" of the CVs. They follow copyright law. Maybe if more people asked, or we had an API on the API page.
