### ISSUE TITLE
Create an RSS feed for new CVs

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#45]

**Comment by andylolz** [comment]
I mainly just wanted this for the [@democlubCVs](https://twitter.com/democlubCVs) twitter bot… That’s now using [sitemap.xml](cv.democracyclub.org.uk/sitemap.xml) instead.

**Comment by frabcus** [comment]
There's also [cvs.json](http://cv.democracyclub.org.uk/cvs.json)

**Comment by andylolz** [comment]
Oh – not sure how I missed that! I’ve modified the bot to use that instead.

**Comment by frabcus** [comment]
I made it for @symroe so he can link to dashboard, and I think YNMP.

I'm not sure where to document it that people will find it! Was hoping a `<link>` tag with JSON mimetype, but apparently nobody looks for those!
