### ISSUE TITLE
Create a JSON dump of all uploaded CVs, keyed on YNMP candidate ID

### ISSUE THREAD

**Issue by symroe** [frabcus/mpcv#46]
Please! :)

This is so we can import the data on a cron in order to import it in to the YNMP super site.

**Comment by frabcus** [comment]
Any particular requirements, or literally JSON with an array of
dicts with all the fields we know about each candidate with a CV?

On Thu, Mar 26, 2015 at 04:44:15AM -0700, Sym Roe wrote:

> Please! :)
> 
> This is so we can import the data on a cron in order to import it in to the YNMP super site.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/frabcus/mpcv/issues/46

## 

Help get every MP candidate's Curriculum Vitae!
http://cv.democracyclub.org.uk/

**Comment by symroe** [comment]
I'm not sure how to present it yet, but enough to be able to display a preview of the CV and a link to the site would be great.  Is there anything else we should include?

**Comment by frabcus** [comment]
Nope, that's pretty well it!

On Thu, Mar 26, 2015 at 05:22:20AM -0700, Sym Roe wrote:

> I'm not sure how to present it yet, but enough to be able to display
> a preview of the CV and a link to the site would be great.  Is there
> anything else we should include?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/frabcus/mpcv/issues/46#issuecomment-86487581

## 

Help get every MP candidate's Curriculum Vitae!
http://cv.democracyclub.org.uk/

**Comment by frabcus** [comment]
@sym, this look good?

``` json
[
    {
        "content_type": "application/octet-stream",
        "last_modified": "2015-03-26T16:50:01",
        "person_id": 6087,
        "has_thumb": true,
        "name": "cvs/6087/2015-03-26T16:50:00-Gareth_Epps_Democracy_Club_CV.doc",
        "created": "2015-03-26T16:44:16",
        "thumb": {
            "content_type": "application/octet-stream",
            "last_modified": "2015-03-26T16:47:39",
            "person_id": 6087,
            "name": "thumbs/6087.jpg",
            "created": "2015-03-26T16:47:39",
            "url": "https://mpcv.s3.amazonaws.com:443/thumbs/6087.jpg"
        },
        "url": "https://mpcv.s3.amazonaws.com:443/cvs/6087/2015-03-26T16%3A50%3A00-Gareth_Epps_Democracy_Club_CV.doc"
    },
```

**Comment by symroe** [comment]
Looks great! I won't know for sure until we consume it in to the real
thing, but this is a great start!

**Comment by frabcus** [comment]
I removed "content_type" (which wasn't working) and "name" (which was redundant and not used). So it is slightly simpler.

Now live at http://cv.democracyclub.org.uk/cvs.json

I'm not sure where to document it without cluttering the site :) Will worry about that later.

**Comment by frabcus** [comment]
Just to note there is one entry in the array for each candidate-with-CV (so it only shows you most recent version if we have older versions of CV)
