### ISSUE TITLE
og:image on `/upload_cv/[ID]` should *not* be latest CV

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#54]
@mhl has pointed out this error e.g.:
http://sphinx.mythic-beasts.com/~mark/weird-twitter-card.png

**Comment by frabcus** [comment]
I feel stuck for inspiration what image to put up instead!

**Comment by andylolz** [comment]
http://cv.democracyclub.org.uk/static/cv_snip.png ?
