### ISSUE TITLE
Add "Uploaded Date" for clarity (e.g. post dissolution MPs)

### ISSUE THREAD

**Issue by tfgg** [frabcus/mpcv#55]
Some CVs include some statement to the effect of the candidate currently being an MP. Obviously this isn't true during the campaign, but might have been true when the CV was uploaded. An upload date on the CV viewing page would clarify this.

**Comment by frabcus** [comment]
It's in the HTML comments.

I'm not sure where to put it without excess clutter, apart from that.

You just need this for lobbying them not to refer to themselves as MP?
