### ISSUE TITLE
Copywriting changes on /candidates page

### ISSUE THREAD

**Issue by JoeMitchell** [frabcus/mpcv#62]
Sorry, couldn't find the original in order to do this as a pull request! 

On /candidates, where it says: 'Not yet submitted their CV" 

Change to: 

Not yet submitted their CV. Please click here to request it from the candidate.

(Then you can remove the text below the CVs ('Good news! ... CVs!" and can lose the Email/Tweet buttons)

The user then clicks on the box, and sees the upload_cv page, where I think the button text could be slightly clearer (if longer): 

Email my candidates to request their CVs
Tweet my candidates to request their CVs

**Comment by frabcus** [comment]
The conversion rate of the big CVs _without_ the text @JoeMitchell suggests is _terrible_ (5 times worse, although sample size small and bank holiday weekend). So am up for trying more to move it on!

Like this now:

![screen shot 2015-04-06 at 23 26 29](https://cloud.githubusercontent.com/assets/10153/7013789/640c94a6-dcb4-11e4-85a5-c2503d6f27fb.png)

I didn't put the "yet" in as it made it feel weak, happy to try again later though!

And the following page:

![screen shot 2015-04-06 at 23 26 57](https://cloud.githubusercontent.com/assets/10153/7013791/735bafc8-dcb4-11e4-8b32-189bed1e1664.png)

**Comment by frabcus** [comment]
That following `/upload_cv` page I think has a bad heading and layout. It is for two purposes - either they are or aren't the candidate.

Fell it could be even more direct.

**Comment by frabcus** [comment]
That's all live now.

**Comment by JoeMitchell** [comment]
Great, looks really good... hope the conversion rates improve!
