### ISSUE TITLE
JSON dump Icon URL broken

### ISSUE THREAD

**Issue by symroe** [frabcus/mpcv#63]
The CSV dump here:

> http://cv.democracyclub.org.uk/cvs.json

Contains, e.g.

``` json
{
    url: "https://mpcv.s3.amazonaws.com:443/thumbs/2948/2015-04-07T09%3A31%3A53-Tom_Rippeth_CV.pdf.jpg",
    created: "2015-04-07T09:27:51",
    last_modified: "2015-04-07T09:37:49",
    name: "thumbs/2948/2015-04-07T09:31:53-Tom_Rippeth_CV.pdf.jpg",
    person_id: 2948
},
```

However 

> http://cv.democracyclub.org.uk/thumbs/2948/2015-04-07T09:31:53-Tom_Rippeth_CV.pdf.jpg

Is a 404.

**Comment by andylolz** [comment]
The URL in `url` works:
https://mpcv.s3.amazonaws.com:443/thumbs/2948/2015-04-07T09%3A31%3A53-Tom_Rippeth_CV.pdf.jpg

I don’t think the thing in `name` will work as a URL – we don’t store copies of any of this stuff on http://cv.democracyclub.org.uk (and I don’t think there are any redirects set up or anything.)

**Comment by symroe** [comment]
Sorry, me being stupid :/
