### ISSUE TITLE
Remove in page back link on CV view

### ISSUE THREAD

**Issue by symroe** [frabcus/mpcv#69]
It's very confusing for people clicking through from YNMP-Read.

**Comment by frabcus** [comment]
Which link do you mean?

**Comment by frabcus** [comment]
Is this the one at the top left which says "More candidates <--". 

People are expecting it to return to YourNextMP are they when it doesn't?

It's very important, I think!, for people who arrive at Democracy Club CVs from search engines, as is only navigation to the rest of the site.

**Comment by frabcus** [comment]
Reopen if this still applies.

**Comment by andylolz** [comment]
Could reword to “More CVs” ?
