### ISSUE TITLE
"Removed after election" isn't "recently added"

### ISSUE THREAD

**Issue by frabcus** [frabcus/mpcv#74]
Front page shows under "recently added" all the "Removed after election" CVs.

Which is just odd in the between-election state.

**Comment by andylolz** [comment]
“Recently added” in general doesn’t really make sense / isn’t really relevant in between elections, though.

**Comment by andylolz** [comment]
Maybe show a random selection instead? Or editors pick?!

**Comment by frabcus** [comment]
Fixed by https://github.com/frabcus/mpcv/commit/b131736d7c1d486d5e66810a339af12853318017

**Comment by andylolz** [comment]
👍
