### ISSUE TITLE
Link to right site for adding candidates

### ISSUE THREAD

**Issue by frabcus** [frabcus/mpcv#79]
It doesn't seem to be HearFromYourMP any more.

**Comment by frabcus** [comment]
Link to from message "No candidates known for your constituency yet." too

**Comment by mhl** [comment]
It should be https://candidates.democracyclub.org.uk/ - it should never have been HearFromYourMP! (I guess you might have meant YourNextMP - http://edit.yournextmp.com now redirects to the current site, https://candidates.democracyclub.org.uk/ )

**Comment by frabcus** [comment]
HearFromYourMP was a typo luckily just in this ticket! All fixed now.
