### ISSUE TITLE
Gives a 500 when no postcode

### ISSUE THREAD

**Issue by pikesley** [frabcus/mpcv#8]
Maybe you already know this, but

On homepage, leave 'Postcode' box blank, click 'View candidates', BOOM!

I would attempt a fix but I don't know from Python :/

**Comment by andylolz** [comment]
Oh! Soz, didn’t spot you’d fixed this, @rossjones!

**Comment by rossjones** [comment]
Think they're complimentary - mine validates on input, yours catchs errors (AND has a test ;) ).

**Comment by andylolz** [comment]
Awesome :)

**Comment by pikesley** [comment]
:)
