### ISSUE TITLE
Make it easier to send follow-up tweets to candidates

### ISSUE THREAD

**Issue by andylolz** [frabcus/mpcv#9]
I’d like to easily be able to send a followup tweet to my candidates – like this:
https://twitter.com/andylolz/status/575281901684027392

This would be easier if twitter handles were pulled through from YourNextMP.

**Comment by frabcus** [comment]
I like this idea.

**Comment by frabcus** [comment]
So, we now email all the candidates at once.

Would you expect a row of Tweet buttons, one to make each Tweet, in the "email sent" page after that?

**Comment by frabcus** [comment]
@andylolz is this covered by the new Tweet all feature, or would you expect the post-email step to offer this directly?

**Comment by frabcus** [comment]
Closing for now!

**Comment by andylolz** [comment]
Yeppers – good call!
