### ISSUE TITLE
Hide "back" button unless user arrived from cvs.democracyclub

### ISSUE THREAD

**Issue by annapowellsmith** [frabcus/mpcv#90]
WCIVF is linking through to CVs, but the back button on cvs.democracyclub is leading to poor UX.

Currently if you're on a page [like this one](https://whocanivotefor.co.uk/person/2567/diane-abbott) and you click on the CV, you see something like this:

<img width="543" alt="screen shot 2017-05-31 at 17 51 36" src="https://cloud.githubusercontent.com/assets/78156/26643623/d052530e-4629-11e7-9569-3de823aef765.png">

If you then click on "More candidates", it bounces you into cvs.democracyclub, which is confusing. Most users won't understand what happened, or how to get back to WCIVF.

Any chance this button could be replaced with "Other candidates' CVs", or the site logo, or removed?

**Comment by andylolz** [comment]
Same issue was raised in 2015 here: #69
